language: python

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/rf24G_receive/rf24G_receive.ino
  - platformio ci --lib="." --board=uno --board=leonardo --board=megaatmega2560 examples/rf24G_send/rf24G_send.ino
